project:
  title: "webr"

#   type: website
#   output-dir: docs
#   resources:
#       - "*.html"
#       - "*.js"
# 
# website:
#   title: "webr"
#   navbar:
#     left:
#       - href: index.qmd
#         text: Home
#       - about.qmd
# 
# format:
#   html:
#     theme: cosmo
#     css: styles.css
#     toc: true
# 
# execute:
#   freeze: auto
# 
# engine: knitr

